apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: aks-appset
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: akuity.io/argo-cd-cluster-name
              operator: NotIn
              values: [in-cluster]
  template:
    metadata:
      name: aks-{{name}}
      namespace: argocd
    spec:
      destination:
        namespace: default
        server: '{{server}}'
      project: default
      source:
        repoURL: 'https://mboersma.github.io/cluster-api-charts'
        chart: azure-aks-aso
        targetRevision: v0.4.2
        helm:
          valuesObject:
            clusterName: '{{name}}'
            location: "westus3"
            subscriptionID: '{{metadata.annotations.subscription_id}}'
            clientID: '{{metadata.annotations.akspe_identity_id}}'
            tenantID: '{{metadata.annotations.tenant_id}}'
            authMode: "workloadidentity"
            kubernetesVersion: v1.30.10
            clusterNetwork: "overlay"
            managedMachinePoolSpecs:
              pool0:
                count: 1
                enableAutoScaling: true
                enableEncryptionAtHost: false
                enableFIPS: false
                enableNodePublicIP: false
                enableUltraSSD: false
                maxCount: 3
                minCount: 1
                mode: System
                osSKU: AzureLinux
                vmSize: Standard_DS2_v2
                type: VirtualMachineScaleSets
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: -1
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 10m
