name: Create Environment when Issue is Opened

on:
  issues:
    types:
      - opened
      - reopened

permissions:
  contents: write
  issues: write

jobs:
  create-environment:
    runs-on: ubuntu-latest

    steps:
    - name: Create Action Start GitHub Issue comment
      uses: peter-evans/create-or-update-comment@v4
      with:
        issue-number: ${{ github.event.issue.number }}
        body: |
          GitHub Action Started.
          GitHub Action Run: [#${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}) to see the logs.
    
    - uses: actions/checkout@v4

    - uses: stefanbuck/github-issue-parser@v3
      id: issue-parser
      with:
        template-path: .github/ISSUE_TEMPLATE/create_cluster.yaml
    
    - name: Create new cluster Application Set Directory
      id: create-application-set-directory
      run: |
        mkdir -p base/clusters/${{github.event.issue.number}}
  
    - name: Create new cluster Application Set YAML
      id: create-application-set-yaml
      uses: cuchi/jinja2-action@v1.3.0
      with:
        template: base/clusters/application_set.yaml.example.jinja
        output_file: base/clusters/${{github.event.issue.number}}/application_set.yaml
      env:
        repoURL: ${{ steps.issue-parser.outputs.issueparser_repoURL }}
        path: ${{ steps.issue-parser.outputs.issueparser_path }}
        targetRevision: ${{ steps.issue-parser.outputs.issueparser_targetRevision }}

    - uses: stefanzweifel/git-auto-commit-action@v5
      id: auto-commit-action
      with:
        commit_message: 'Add new cluster Application Set for Issue #${{github.event.issue.number}}'
        branch: main
        file_pattern: 'base/clusters/${{github.event.issue.number}}/*'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create success comment
      uses: peter-evans/create-or-update-comment@v4
      if: success()
      with:
        issue-number: ${{ github.event.issue.number }}
        body: |
          SUCCESS: The Application Set succeeded to create via issue #${{ github.event.issue.number }}.
          GitHub Action Run: [#${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}) to see the logs.
          Commit SHA: ${{ github.steps.auto-commit-action.outputs.commit_hash || 'No Changes Made'}}

    - name: Close Issue
      uses: peter-evans/close-issue@v3
      with:
        issue-number: ${{ github.event.issue.number }}
        comment: 'Auto-closing issue #${{ github.event.issue.number }} after creating the Application Set.'

    
    - name: Create failure comment
      uses: peter-evans/create-or-update-comment@v4
      if: failure()
      with:
        issue-number: ${{ github.event.issue.number }}
        body: |
          FAILURE: The Application Set failed to create.
          Run [#${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}) to see the logs.